# Generated by Django 3.0.1 on 2019-12-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundesinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstandings',
            name='matchday',
        ),
    ]
