# Generated by Django 3.0.1 on 2019-12-23 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundesinfo', '0002_remove_teamstandings_matchday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstandings',
            name='draws',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(34)]),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='loses',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(34)]),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='points',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='wins',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(34)]),
        ),
    ]
