# Generated by Django 3.0.1 on 2019-12-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundesinfo', '0003_auto_20191223_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamstandings',
            options={'ordering': ('-points', '-wins')},
        ),
    ]
